#!/bin/bash
#PBS -N 6_scaling_test
#PBS -l select=1:ncpus=8
#PBS -q small
# Options for -q on mozzie include: small, large
#PBS -o logs/
#PBS -e logs/
#PBS -m ae
# Optional: adjust email on (on new line): #PBS -M your.email@example.com

# If you want your script to stop if any command fails, uncomment:
# set -e

cd "$PBS_O_WORKDIR"

echo "Running on:"
hostname
echo "Working directory:"
pwd
echo "Job ID:"
echo "$PBS_JOBID"
echo "Allocated CPUs:"
echo "$PBS_NCPUS"

python code/scaling_test.py

echo "Job finished successfully."
